name: Build and Test

on: [push]

jobs:
  LinuxUbuntu18:
    name: Ubuntu 18.04

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: |
        sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ bionic main restricted" >> /etc/apt/sources.lst'
        sudo apt-get install ccache flex bison

    - uses: actions/checkout@v1

    - name: git submodules
      run: |
        git submodule set-url lib/cbmc https://github.com/diffblue/cbmc/
        git submodule set-url regression/oracles https://github.com/polgreen/oracles/
        git -c "http.extraheader=Authorization: basic ${GITHUB_ACCESS_TOKEN}" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: cache for ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.[(cpp)ch]') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: ccache stats
      run: ccache -s --max-size=390MB

    - name: MiniSat
      run: make -C lib/cbmc/src minisat2-download 

    - name: make
      run: make -C src -j2 CXX="ccache g++"

    - name: regression tests
      run: make -C regression
